version: '3.7'

services:

  tgbot:
    container_name: tgbot
    build:
      context: ./$APP_BASE_DIR
      args:
        APP_BASE_DIR: $APP_BASE_DIR
    command: python app.py
    volumes:
      - ./$SSL_DIR$SSL_CERT:/$APP_BASE_DIR/$SSL_DIR$SSL_CERT:ro
      - ./$SSL_DIR$SSL_PRIV:/$APP_BASE_DIR/$SSL_DIR$SSL_PRIV:ro
    env_file:
      - .env
    ports:
      - $WEBHOOK_PORT:$WEBAPP_PORT
    networks:
      - tgbot_backend
    restart: always


networks:
  tgbot_backend:
